@TestOn('vm')
library;

import 'dart:convert';
import 'dart:io';

import 'package:dart_boost/src/cli/dialog_support.dart';
import 'package:dart_boost/src/cli/runner.dart';
import 'package:dart_boost/src/util/logger.dart';
import 'package:dart_boost/src/util/process_runner.dart';
import 'package:path/path.dart' as p;
import 'package:test/test.dart';
import 'package:test_descriptor/test_descriptor.dart' as d;

/// Phase 5's CLI surface: prompts, `update`'s dependency discovery, and the
/// `package:skills` hand-off -- all on a real filesystem, with only the
/// process boundary and the terminal stubbed.
void main() {
  late List<String> output;
  late FakeProcessRunner processes;

  setUp(() {
    output = <String>[];
    processes = FakeProcessRunner({
      'dart mcp-server --version': const ProcessOutcome(
        0,
        'dart mcp-server 1.0',
        '',
      ),
    });
  });

  Future<int> run(
    List<String> args, {
    DialogSupport? dialogs,
    Map<String, String> environment = const <String, String>{},
  }) async =>
      await DartBoostRunner(
        processRunner: processes,
        logger: BoostLogger.buffered(output),
        dialogs: dialogs ?? const NonInteractiveDialogSupport(),
        environment: environment,
        isWindows: false,
      ).run(args) ??
      0;

  String appDir() => p.join(d.sandbox, 'app');

  File appFile(String relative) =>
      File(p.join(appDir(), p.joinAll(relative.split('/'))));

  /// A Flutter project whose dependency set can be rewritten between runs, so
  /// `update` has something to discover.
  Future<void> project({
    Map<String, String> dependencies = const <String, String>{
      'riverpod': '3.0.1',
    },
    bool create = true,
  }) async {
    final pubspec =
        StringBuffer()
          ..writeln('name: my_app')
          ..writeln('environment:')
          ..writeln("  sdk: '>=3.5.0 <4.0.0'")
          ..writeln('dependencies:')
          ..writeln('  flutter:\n    sdk: flutter');
    final lock =
        StringBuffer()
          ..writeln('# Generated by pub')
          ..writeln('packages:');
    dependencies.forEach((name, version) {
      pubspec.writeln('  $name: ^$version');
      lock
        ..writeln('  $name:')
        ..writeln('    dependency: "direct main"')
        ..writeln('    description:')
        ..writeln('      name: $name')
        ..writeln('      url: "https://pub.dev"')
        ..writeln('    source: hosted')
        ..writeln('    version: "$version"');
    });
    pubspec.writeln('flutter:\n  uses-material-design: true');
    lock.writeln('sdks:\n  dart: ">=3.5.0 <4.0.0"');

    if (create) {
      await d.dir('app', [
        d.dir('.dart_tool', [
          d.file('version', '3.47.2'),
          d.file(
            'package_config.json',
            jsonEncode(<String, Object?>{
              'configVersion': 2,
              'generator': 'pub',
              'generatorVersion': '3.13.2',
              'packages': <Object?>[],
            }),
          ),
        ]),
      ]).create();
    }
    appFile('pubspec.yaml').writeAsStringSync(pubspec.toString());
    appFile('pubspec.lock').writeAsStringSync(lock.toString());
  }

  Map<String, Object?> state() =>
      jsonDecode(appFile('dart_boost.json').readAsStringSync())
          as Map<String, Object?>;

  /// The per-machine observations, split out of `dart_boost.json` into
  /// `.dart_tool/dart_boost/state.json` -- gitignored, unlike [state].
  Map<String, Object?> machineState() =>
      jsonDecode(appFile('.dart_tool/dart_boost/state.json').readAsStringSync())
          as Map<String, Object?>;

  group('interactive selection', () {
    test('writes only what the multiselect returned', () async {
      await project();
      // Index 0 is Claude Code, and nothing else is picked, so `.cursor/` and
      // friends must stay absent.
      final dialogs = FakeDialogSupport(
        selections: <Set<int>?>[
          <int>{0},
        ],
        confirmations: <bool>[true],
      );

      final code = await run(['-C', appDir(), 'install'], dialogs: dialogs);

      expect(code, 0);
      expect(appFile('CLAUDE.md').existsSync(), isTrue);
      expect(appFile('AGENTS.md').existsSync(), isFalse);
      expect(state()['agents'], <String>['claude_code']);
    });

    test('a cancelled multiselect writes nothing', () async {
      await project();

      final code = await run([
        '-C',
        appDir(),
        'install',
      ], dialogs: FakeDialogSupport(selections: const <Set<int>?>[null]));

      expect(code, 0);
      expect(appFile('CLAUDE.md').existsSync(), isFalse);
      expect(appFile('dart_boost.json').existsSync(), isFalse);
    });

    test('declining the confirmation writes nothing', () async {
      await project();
      final dialogs = FakeDialogSupport(
        selections: <Set<int>?>[
          <int>{0},
        ],
        confirmations: <bool>[false],
      );

      final code = await run(['-C', appDir(), 'install'], dialogs: dialogs);

      expect(code, 0);
      expect(dialogs.questions.single, 'Proceed?');
      expect(output.join('\n'), contains('CLAUDE.md'));
      expect(appFile('CLAUDE.md').existsSync(), isFalse);
      expect(appFile('dart_boost.json').existsSync(), isFalse);
    });

    test('--yes asks nothing', () async {
      await project();
      final dialogs = FakeDialogSupport(
        selections: <Set<int>?>[<int>{}],
        confirmations: <bool>[false],
      );

      await run([
        '-C',
        appDir(),
        'install',
        '--agents=claude_code',
        '--yes',
      ], dialogs: dialogs);

      expect(dialogs.questions, isEmpty);
      expect(appFile('CLAUDE.md').existsSync(), isTrue);
    });

    test('CI skips the prompts even though the dialogs claim a TTY', () async {
      await project();
      // The real hazard: a CI runner with a pty attached. `hasTerminal` is
      // true there, so without an environment check this run would block
      // forever on a multiselect no one can answer.
      final dialogs = FakeDialogSupport(
        selections: <Set<int>?>[<int>{}],
        confirmations: <bool>[false],
      );

      final code = await run(
        ['-C', appDir(), 'install', '--agents=claude_code'],
        dialogs: dialogs,
        environment: const <String, String>{'CI': 'true'},
      );

      expect(code, 0);
      expect(dialogs.questions, isEmpty);
      expect(appFile('CLAUDE.md').existsSync(), isTrue);
    });

    test('CI=false is a deliberate opt-out and still prompts', () async {
      await project();
      final dialogs = FakeDialogSupport(confirmations: <bool>[false]);

      await run(
        ['-C', appDir(), 'install', '--agents=claude_code'],
        dialogs: dialogs,
        environment: const <String, String>{'CI': 'false'},
      );

      expect(dialogs.questions, <String>['Proceed?']);
    });

    test(
      '--dry-run does not ask to confirm a write it will not make',
      () async {
        await project();
        final dialogs = FakeDialogSupport(confirmations: <bool>[false]);

        final code = await run([
          '-C',
          appDir(),
          '--dry-run',
          'install',
          '--agents=claude_code',
        ], dialogs: dialogs);

        expect(code, 0);
        expect(dialogs.questions, isEmpty);
        expect(appFile('CLAUDE.md').existsSync(), isFalse);
      },
    );
  });

  group('update dependency discovery', () {
    Future<void> installed() async {
      await project();
      await run(['-C', appDir(), 'install', '--agents=claude_code', '--yes']);
      output.clear();
    }

    test('install records the dependencies and fragments it saw', () async {
      await installed();

      // `flutter` is a direct dependency with no resolvable version -- adding
      // or dropping it changes the composed guidance, so it is recorded as
      // `-` rather than omitted.
      expect(machineState()['dependencies'], <String, String>{
        'flutter': '-',
        'riverpod': '3.0.1',
      });
      expect(machineState()['fragments'], contains('riverpod/v3'));
    });

    test(
      'reports a dependency added since the last run, and its guidance',
      () async {
        await installed();
        await project(
          dependencies: const <String, String>{
            'riverpod': '3.0.1',
            'go_router': '18.0.1',
          },
          create: false,
        );

        final code = await run(['-C', appDir(), 'update', '--yes']);

        expect(code, 0);
        final report = output.join('\n');
        expect(report, contains('+ go_router 18.0.1'));
        expect(report, contains('go_router/v18'));
        // And the fragment it brought is actually installed, not just announced.
        expect(
          appFile('CLAUDE.md').readAsStringSync(),
          contains('=== go_router/v18 rules ==='),
        );
        expect(machineState()['fragments'], contains('go_router/v18'));
      },
    );

    test(
      'reports a removed dependency and the guidance that went with it',
      () async {
        await installed();
        await project(
          dependencies: const <String, String>{'go_router': '18.0.1'},
          create: false,
        );

        await run(['-C', appDir(), 'update', '--yes']);

        final report = output.join('\n');
        expect(report, contains('- riverpod 3.0.1'));
        expect(report, contains('no longer applies'));
        expect(report, contains('riverpod/v3'));
        expect(
          appFile('CLAUDE.md').readAsStringSync(),
          isNot(contains('=== riverpod/v3 rules ===')),
        );
      },
    );

    test('a major bump is reported; a patch bump is not', () async {
      await installed();
      await project(
        dependencies: const <String, String>{'riverpod': '3.0.2'},
        create: false,
      );
      await run(['-C', appDir(), 'update', '--yes']);
      expect(
        output.join('\n'),
        isNot(contains('Dependencies since the last run')),
      );

      output.clear();
      await project(
        dependencies: const <String, String>{'riverpod': '2.6.1'},
        create: false,
      );
      await run(['-C', appDir(), 'update', '--yes']);

      final report = output.join('\n');
      expect(report, contains('riverpod 3.0.2 -> 2.6.1'));
      expect(report, contains('different guidance applies'));
      expect(report, contains('riverpod/v2'));
    });

    test(
      'a state file with no recorded dependencies claims no drift',
      () async {
        await installed();
        // What a machine state file from before this field existed looks like.
        // Every dependency is "new" relative to an empty baseline, and saying
        // so would be the loudest possible way to be wrong.
        final legacy = machineState()..remove('dependencies');
        appFile(
          '.dart_tool/dart_boost/state.json',
        ).writeAsStringSync(jsonEncode(legacy));

        await run(['-C', appDir(), 'update', '--yes']);

        expect(output.join('\n'), isNot(contains('+ riverpod')));
        expect(machineState()['dependencies'], isNotEmpty);
      },
    );

    test('update repeats the saved answers without prompting', () async {
      await installed();
      final dialogs = FakeDialogSupport(
        selections: <Set<int>?>[<int>{}],
        confirmations: <bool>[false],
      );

      final code = await run(['-C', appDir(), 'update'], dialogs: dialogs);

      expect(code, 0);
      expect(dialogs.questions, isEmpty);
      expect(state()['agents'], <String>['claude_code']);
    });
  });

  group('skills delegation', () {
    Future<void> withSkillsDependency() async {
      await project(
        dependencies: const <String, String>{
          'riverpod': '3.0.1',
          'skills': '0.1.0',
        },
      );
    }

    test('runs the hand-off and remembers the consent', () async {
      await withSkillsDependency();
      processes.responses['dart run skills get'] = const ProcessOutcome(
        0,
        'fetched 2 skills',
        '',
      );

      final code = await run([
        '-C',
        appDir(),
        'install',
        '--agents=claude_code',
        '--yes',
      ]);

      expect(code, 0);
      expect(processes.invocations, contains('dart run skills get'));
      expect(state()['delegateSkills'], isTrue);
    });

    test('an absent skills leaves the install successful and silent', () async {
      await project();

      final code = await run([
        '-C',
        appDir(),
        'install',
        '--agents=claude_code',
        '--yes',
      ]);

      expect(code, 0);
      expect(appFile('CLAUDE.md').existsSync(), isTrue);
      expect(output.join('\n'), isNot(contains('Skills')));
      expect(state()['delegateSkills'], isFalse);
    });

    test('a failing skills run does not fail the install', () async {
      await withSkillsDependency();
      processes.responses['dart run skills get'] = const ProcessOutcome(
        1,
        '',
        'could not resolve',
      );

      final code = await run([
        '-C',
        appDir(),
        'install',
        '--agents=claude_code',
        '--yes',
      ]);

      expect(code, 0);
      expect(appFile('CLAUDE.md').existsSync(), isTrue);
      expect(output.join('\n'), contains('written regardless'));
      // A failure is not the user declining, so the answer on file is unchanged.
      expect(state()['delegateSkills'], isFalse);
    });

    test('--no-skills suppresses it', () async {
      await withSkillsDependency();
      processes.responses['dart run skills get'] = const ProcessOutcome(
        0,
        '',
        '',
      );

      await run([
        '-C',
        appDir(),
        'install',
        '--agents=claude_code',
        '--yes',
        '--no-skills',
      ]);

      expect(processes.invocations, isNot(contains('dart run skills get')));
    });

    test('--dry-run reports the hand-off without running it', () async {
      await withSkillsDependency();
      processes.responses['dart run skills get'] = const ProcessOutcome(
        0,
        '',
        '',
      );

      await run([
        '-C',
        appDir(),
        '--dry-run',
        'install',
        '--agents=claude_code',
        '--yes',
      ]);

      expect(processes.invocations, isNot(contains('dart run skills get')));
      expect(output.join('\n'), contains('would run `dart run skills get`'));
    });

    test('a declined offer runs nothing and is recorded as such', () async {
      await withSkillsDependency();
      processes.responses['dart run skills get'] = const ProcessOutcome(
        0,
        '',
        '',
      );
      final dialogs = FakeDialogSupport(
        selections: <Set<int>?>[
          <int>{0},
        ],
        // Proceed?, then decline adding dart_boost as a dev dependency (this
        // project has no dart_boost dependency, so rules wiring also asks),
        // then decline the skills hand-off.
        confirmations: <bool>[true, false, false],
      );

      await run(['-C', appDir(), 'install'], dialogs: dialogs);

      // Three questions, in order: plan confirmation, rules wiring, skills.
      // Asserting the count (not just `.last`) is what catches a rules path
      // that silently stops asking -- with only two questions, `[1]=false`
      // would answer the *skills* question instead and every other
      // assertion here would still pass.
      expect(dialogs.questions, hasLength(3));
      expect(dialogs.questions[0], 'Proceed?');
      expect(
        dialogs.questions[1],
        allOf(contains('dart_boost'), contains('dev dependency')),
      );
      expect(dialogs.questions.last, contains('dart run skills get'));
      expect(processes.invocations, isNot(contains('dart run skills get')));
      expect(
        processes.invocations,
        isNot(contains('dart pub add dev:dart_boost')),
      );
      // `delegateSkills` records consent, not a decision: false means "has not
      // agreed", so the next interactive install asks again rather than
      // treating one "no" as permanent.
      expect(state()['delegateSkills'], isFalse);
    });
  });
}
