@TestOn('vm')
library;

import 'dart:convert';
import 'dart:io';

import 'package:dart_boost/src/cli/dialog_support.dart';
import 'package:dart_boost/src/cli/runner.dart';
import 'package:dart_boost/src/util/logger.dart';
import 'package:dart_boost/src/util/process_runner.dart';
import 'package:dart_boost/src/writers/json_splicer.dart';
import 'package:path/path.dart' as p;
import 'package:test/test.dart';
import 'package:test_descriptor/test_descriptor.dart' as d;
import 'package:toml/toml.dart';

/// The whole CLI, on a real filesystem.
///
/// Deliberately *not* run on `MemoryFileSystem`: install shells out to `dart`
/// and `command -v`, which do not participate in that abstraction. Only the
/// process boundary is stubbed.
void main() {
  late List<String> output;
  late FakeProcessRunner processes;

  setUp(() {
    output = <String>[];
    processes = FakeProcessRunner({
      'dart mcp-server --version': const ProcessOutcome(
        0,
        'dart mcp-server 1.0',
        '',
      ),
    });
  });

  Future<int> run(List<String> args) async =>
      await DartBoostRunner(
        processRunner: processes,
        logger: BoostLogger.buffered(output),
        dialogs: const NonInteractiveDialogSupport(),
        environment: const <String, String>{},
        isWindows: false,
      ).run(args) ??
      0;

  Future<void> flutterProject({String? claudeMd, String? mcpJson}) async {
    await d.dir('app', [
      d.file('pubspec.yaml', '''
name: my_app
environment:
  sdk: '>=3.5.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  riverpod: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
flutter:
  uses-material-design: true
'''),
      d.file('pubspec.lock', '''
# Generated by pub
packages:
  riverpod:
    dependency: "direct main"
    description:
      name: riverpod
      url: "https://pub.dev"
    source: hosted
    version: "3.0.1"
  build_runner:
    dependency: "direct dev"
    description:
      name: build_runner
      url: "https://pub.dev"
    source: hosted
    version: "2.4.9"
  meta:
    dependency: transitive
    description:
      name: meta
      url: "https://pub.dev"
    source: hosted
    version: "1.15.0"
sdks:
  dart: ">=3.5.0 <4.0.0"
'''),
      d.dir('.dart_tool', [
        d.file('version', '3.47.2'),
        d.file(
          'package_config.json',
          jsonEncode(<String, Object?>{
            'configVersion': 2,
            'generator': 'pub',
            'generatorVersion': '3.13.2',
            'packages': <Object?>[],
          }),
        ),
      ]),
      if (claudeMd != null) d.file('CLAUDE.md', claudeMd),
      if (mcpJson != null) d.file('.mcp.json', mcpJson),
    ]).create();
  }

  String read(String relative) =>
      File(
        p.join(d.sandbox, 'app', p.joinAll(relative.split('/'))),
      ).readAsStringSync();

  bool exists(String relative) =>
      File(
        p.join(d.sandbox, 'app', p.joinAll(relative.split('/'))),
      ).existsSync();

  String appDir() => p.join(d.sandbox, 'app');

  group('install', () {
    test('writes guidelines and an MCP entry for the named agents', () async {
      await flutterProject();

      final code = await run([
        '-C',
        appDir(),
        'install',
        '--agents=claude_code',
        '--yes',
      ]);

      expect(code, 0, reason: output.join('\n'));

      final guidelines = read('CLAUDE.md');
      expect(guidelines, contains('<dart-boost-guidelines>'));
      expect(guidelines, contains('=== foundation rules ==='));
      // Version-keyed: the project resolves Riverpod 3, so the v3 fragment is
      // what lands, not the v2 one.
      expect(guidelines, contains('=== riverpod/v3 rules ==='));
      expect(guidelines, isNot(contains('=== riverpod/v2 rules ===')));
      expect(guidelines, contains('=== flutter/v3.47 rules ==='));
      // build_runner is a direct dev dependency, so the codegen block renders.
      expect(
        guidelines,
        contains('build_runner build --delete-conflicting-outputs'),
      );
      // No unrendered directives or variables survive.
      expect(guidelines, isNot(contains('boost:if')));
      expect(guidelines, isNot(contains(RegExp(r'\{\{\s*\w+\s*\}\}'))));

      final mcp = jsonDecode(read('.mcp.json')) as Map<String, Object?>;
      expect(mcp['mcpServers'], {
        'dart': {
          'command': 'dart',
          'args': ['mcp-server'],
        },
      });
    });

    test('preserves user content in a pre-existing guidelines file', () async {
      await flutterProject(
        claudeMd: '# House rules\n\nAlways ask before deleting.\n',
      );

      await run(['-C', appDir(), 'install', '--agents=claude_code', '--yes']);

      final guidelines = read('CLAUDE.md');
      expect(guidelines, contains('# House rules'));
      expect(guidelines, contains('Always ask before deleting.'));
      expect(
        guidelines.indexOf('House rules'),
        lessThan(guidelines.indexOf('<dart-boost-guidelines>')),
      );
    });

    test(
      'preserves other servers and comments in a pre-existing MCP config',
      () async {
        await flutterProject(
          mcpJson: '''
{
  // Managed by hand. Do not reformat.
  "mcpServers": {
    "filesystem": {
      "command": "npx",
      "args": ["-y", "@modelcontextprotocol/server-filesystem", "."]
    }
  }
}
''',
        );

        await run(['-C', appDir(), 'install', '--agents=claude_code', '--yes']);

        final config = read('.mcp.json');
        expect(config, contains('// Managed by hand. Do not reformat.'));

        final decoded =
            jsonDecode(JsonConfigSplicer.toStrictJson(config))
                as Map<String, Object?>;
        final servers = decoded['mcpServers']! as Map<String, Object?>;
        expect(servers.keys, containsAll(<String>['filesystem', 'dart']));
        expect((servers['filesystem']! as Map)['args'], [
          '-y',
          '@modelcontextprotocol/server-filesystem',
          '.',
        ]);

        // The original is recoverable.
        expect(exists('.mcp.json.dart-boost.bak'), isTrue);
      },
    );

    test('writes AGENTS.md once for the agents that share it', () async {
      await flutterProject();

      await run([
        '-C',
        appDir(),
        'install',
        '--agents=cursor,codex,windsurf',
        '--yes',
      ]);

      final agentsMd = read('AGENTS.md');
      expect(
        GuidelinesSentinel.count(agentsMd),
        1,
        reason: 'three agents share AGENTS.md; the block must be written once',
      );
    });

    test('honours each agent\'s config key, path and entry shape', () async {
      await flutterProject();

      await run([
        '-C',
        appDir(),
        'install',
        '--agents=copilot,codex,zed,opencode',
        '--yes',
      ]);

      final vscode =
          jsonDecode(read('.vscode/mcp.json')) as Map<String, Object?>;
      expect(
        (vscode['servers']! as Map)['dart'],
        containsPair('type', 'stdio'),
      );

      final codex = TomlDocument.parse(read('.codex/config.toml')).toMap();
      expect((codex['mcp_servers']! as Map)['dart'], {
        'command': 'dart',
        'args': ['mcp-server'],
      });

      final zed =
          jsonDecode(read('.zed/settings.json')) as Map<String, Object?>;
      expect(
        (zed['context_servers']! as Map)['dart'],
        containsPair('source', 'custom'),
      );

      final opencode =
          jsonDecode(read('opencode.json')) as Map<String, Object?>;
      expect((opencode['mcp']! as Map)['dart'], containsPair('type', 'local'));
    });

    test('is idempotent -- a second run changes nothing', () async {
      await flutterProject(claudeMd: '# House rules\n');

      await run([
        '-C',
        appDir(),
        'install',
        '--agents=claude_code,codex',
        '--yes',
      ]);
      final first = <String, String>{
        for (final f in <String>[
          'CLAUDE.md',
          'AGENTS.md',
          '.mcp.json',
          '.codex/config.toml',
          'dart_boost.json',
        ])
          f: read(f),
      };

      await run([
        '-C',
        appDir(),
        'install',
        '--agents=claude_code,codex',
        '--yes',
      ]);

      first.forEach(
        (file, content) => expect(read(file), content, reason: file),
      );
    });

    test('persists what it chose, so update can repeat it', () async {
      await flutterProject();

      await run(['-C', appDir(), 'install', '--agents=claude_code', '--yes']);

      final state = jsonDecode(read('dart_boost.json')) as Map<String, Object?>;
      expect(state['agents'], ['claude_code']);
      expect(state['features'], {'guidelines': true, 'mcp': true});
      expect(state['lastRun'], containsPair('flutter', '3.47.2'));
      expect(state['lastRun'], containsPair('dart', '3.13.2'));
    });

    test('--dry-run touches nothing', () async {
      await flutterProject();

      final code = await run([
        '-C',
        appDir(),
        '--dry-run',
        'install',
        '--agents=claude_code',
        '--yes',
      ]);

      expect(code, 0);
      expect(exists('CLAUDE.md'), isFalse);
      expect(exists('.mcp.json'), isFalse);
      expect(exists('dart_boost.json'), isFalse);
      expect(output.join('\n'), contains('Dry run'));
    });

    test('--no-mcp writes guidelines only', () async {
      await flutterProject();

      await run([
        '-C',
        appDir(),
        'install',
        '--agents=claude_code',
        '--yes',
        '--no-mcp',
      ]);

      expect(exists('CLAUDE.md'), isTrue);
      expect(exists('.mcp.json'), isFalse);
    });

    test(
      'warns rather than failing when the MCP server does not answer',
      () async {
        await flutterProject();
        processes.responses.remove('dart mcp-server --version');

        final code = await run([
          '-C',
          appDir(),
          'install',
          '--agents=claude_code',
          '--yes',
        ]);

        // `dart mcp-server` is a hidden subcommand, so no response may just mean
        // an older SDK. Configure anyway, and say so.
        expect(code, 0);
        expect(output.join('\n'), contains('hidden'));
        expect(exists('.mcp.json'), isTrue);
      },
    );
  });

  group('update', () {
    test('refuses before an install has happened', () async {
      await flutterProject();

      final code = await run(['-C', appDir(), 'update', '--yes']);

      expect(code, 64);
      expect(output.join('\n'), contains('dart_boost install'));
    });

    test('repeats the saved agents and reports SDK drift', () async {
      await flutterProject();
      await run(['-C', appDir(), 'install', '--agents=claude_code', '--yes']);

      File(
        p.join(appDir(), '.dart_tool', 'version'),
      ).writeAsStringSync('3.44.9');
      output.clear();
      final code = await run(['-C', appDir(), 'update', '--yes']);

      expect(code, 0);
      expect(output.join('\n'), contains('Flutter 3.47.2 -> 3.44.9'));
      // The composed guidelines follow the new SDK minor.
      expect(read('CLAUDE.md'), isNot(contains('=== flutter/v3.47 rules ===')));
      expect(
        jsonDecode(read('dart_boost.json')),
        containsPair('lastRun', containsPair('flutter', '3.44.9')),
      );
    });
  });

  group('compose and doctor', () {
    test('compose prints without writing anything', () async {
      await flutterProject();

      final code = await run(['-C', appDir(), 'compose']);

      expect(code, 0);
      expect(output.join('\n'), contains('=== foundation rules ==='));
      expect(exists('CLAUDE.md'), isFalse);
    });

    test('compose --keys lists what matched', () async {
      await flutterProject();

      await run(['-C', appDir(), 'compose', '--keys']);

      expect(output, contains('riverpod/v3'));
      expect(output, contains('flutter/v3.47'));
    });

    test('doctor reports where each fact came from', () async {
      await flutterProject();

      final code = await run(['-C', appDir(), 'doctor', '--no-agents']);

      expect(code, 0);
      final report = output.join('\n');
      expect(report, contains('.dart_tool/version'));
      expect(report, contains('pubspec.lock'));
      expect(report, contains('3.47.2'));
      expect(report, contains('dart mcp-server'));
    });
  });

  test('--version prints the version', () async {
    expect(await run(['--version']), 0);
    expect(output.single, startsWith('dart_boost '));
  });
}

abstract final class GuidelinesSentinel {
  static int count(String content) =>
      RegExp('<dart-boost-guidelines>').allMatches(content).length;
}
