import 'dart:convert';
import 'dart:io' show Platform;

import 'package:file/file.dart';
import 'package:file/memory.dart';
import 'package:path/path.dart' as p;

/// A `MemoryFileSystem` whose path style matches the host, so `package:path`'s
/// host-style joins (which the library uses everywhere) line up on Windows too.
MemoryFileSystem memoryFs() => MemoryFileSystem(
  style: Platform.isWindows ? FileSystemStyle.windows : FileSystemStyle.posix,
);

/// Builds a plausible on-disk Dart/Flutter project in memory.
class FakeProject {
  FakeProject(this.fileSystem, String path)
    : root = fileSystem.directory(path)..createSync(recursive: true);

  final FileSystem fileSystem;
  final Directory root;

  String get path => root.path;

  void write(String relative, String content) {
    final file = fileSystem.file(
      p.join(root.path, p.joinAll(relative.split('/'))),
    );
    file.parent.createSync(recursive: true);
    file.writeAsStringSync(content);
  }

  void writeJson(String relative, Object? value) =>
      write(relative, '${const JsonEncoder.withIndent('  ').convert(value)}\n');

  void pubspec({
    String name = 'my_app',
    bool flutter = true,
    Map<String, String> dependencies = const <String, String>{},
    Map<String, String> devDependencies = const <String, String>{},
    String? extra,
  }) {
    final buffer =
        StringBuffer()
          ..writeln('name: $name')
          ..writeln('environment:')
          ..writeln("  sdk: '>=3.5.0 <4.0.0'")
          ..writeln('dependencies:');
    if (flutter) buffer.writeln('  flutter:\n    sdk: flutter');
    dependencies.forEach((key, value) => buffer.writeln('  $key: $value'));
    buffer.writeln('dev_dependencies:');
    if (flutter) buffer.writeln('  flutter_test:\n    sdk: flutter');
    devDependencies.forEach((key, value) => buffer.writeln('  $key: $value'));
    if (flutter) buffer.writeln('flutter:\n  uses-material-design: true');
    if (extra != null) buffer.writeln(extra);
    write('pubspec.yaml', buffer.toString());
  }

  /// [packages] maps name -> `'<version> <dependency-kind>'`, e.g.
  /// `'2.6.1 direct main'`. Note `transitive` is emitted unquoted and the
  /// others quoted, exactly as pub writes them.
  void lock(Map<String, String> packages) {
    final buffer =
        StringBuffer()
          ..writeln('# Generated by pub')
          ..writeln('packages:');
    packages.forEach((name, spec) {
      final parts = spec.split(' ');
      final version = parts.first;
      final kind = parts.skip(1).join(' ');
      final rendered = kind == 'transitive' ? 'transitive' : '"$kind"';
      buffer
        ..writeln('  $name:')
        ..writeln('    dependency: $rendered')
        ..writeln('    description:')
        ..writeln('      name: $name')
        ..writeln('      url: "https://pub.dev"')
        ..writeln('    source: hosted')
        ..writeln('    version: "$version"');
    });
    buffer
      ..writeln('sdks:')
      ..writeln('  dart: ">=3.5.0 <4.0.0"');
    write('pubspec.lock', buffer.toString());
  }

  void packageGraph({
    required String rootName,
    List<String> dependencies = const <String>[],
    List<String> devDependencies = const <String>[],
  }) => writeJson('.dart_tool/package_graph.json', <String, Object?>{
    'roots': <String>[rootName],
    'packages': <Object?>[
      <String, Object?>{
        'name': rootName,
        'version': '1.0.0',
        'dependencies': dependencies,
        'devDependencies': devDependencies,
      },
    ],
    'configVersion': 1,
  });

  /// Values in [packages] are absolute directory paths. Pass [relative] to
  /// write them the way pub actually does for the root package, path
  /// dependencies and workspace members -- as a `rootUri` relative to
  /// `.dart_tool/`.
  void packageConfig({
    Map<String, String> packages = const <String, String>{},
    String generatorVersion = '3.13.2',
    bool relative = false,
  }) => writeJson('.dart_tool/package_config.json', <String, Object?>{
    'configVersion': 2,
    'generator': 'pub',
    'generatorVersion': generatorVersion,
    'packages': <Object?>[
      for (final entry in packages.entries)
        <String, Object?>{
          'name': entry.key,
          'rootUri':
              relative
                  ? p.url.joinAll(
                    p
                        .split(
                          p.relative(
                            entry.value,
                            from: p.join(root.path, '.dart_tool'),
                          ),
                        )
                        .followedBy(<String>['']),
                  )
                  : fileSystem.directory(entry.value).uri.toString(),
          'packageUri': 'lib/',
        },
    ],
  });

  void dartToolVersion(String version) => write('.dart_tool/version', version);
}
